# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='social_respon',
            field=models.TextField(max_length=500, null=True, verbose_name='Social responsibility'),
        ),
    ]
