# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_auto_20170303_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='nit',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
