# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_auto_20170303_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='timestamps',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
