# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_enterprise_timestamps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='timestamps',
            new_name='created_at',
        ),
    ]
