# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
