# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20170311_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='related_dir',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
