# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20170312_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
