# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='observations',
            field=models.TextField(null=True),
        ),
    ]
