# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
