# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0002_profile_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
                ('lat', models.IntegerField(default=0)),
                ('lon', models.IntegerField(default=0)),
            ],
        ),
    ]
