# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='date',
            field=models.DateField(default=datetime.date(2017, 2, 24)),
        ),
    ]
