# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0004_ruta_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 24, 15, 0, 31, 126792, tzinfo=utc)),
        ),
    ]
