# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0005_auto_20170224_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
