# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('observations', models.TextField()),
                ('admin_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise')),
            ],
        ),
    ]
