# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_service_admin_by'),
        ('service', '0003_auto_20170313_0211'),
    ]

    operations = [
    ]
